### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by sashaankadibhatla** [yahoo/egads#51]
i installed the latest version of java JDK and maven on win10, then i successfully compiled using command mvn clean compile assembly:single, but when i type this
java -Dlog4j.configurationFile=src/test/resources/log4j2.xml -cp target/egads-*-jar-with-dependencies.jar com.yahoo.egads.Egads src/test/resources/sample_config.ini src/test/resources/sample_input.csv
an error occurs:
Error: Could not find or load main class com.yahoo.egads.Egads
Caused by: java.lang.ClassNotFoundException: com.yahoo.egads.Egads

**Comment by jigs1993** [comment]
I think this might be your class-path entry in MANIFEST.MF, can you try specifying main class file com.yahoo.egads.Egads in pom.xml and build again

**Comment by sashaankadibhatla** [comment]
<plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.0</version>
              <configuration>
                <source>1.8</source>
                <target>1.8</target>
		<archive>
			<manifest>
				<mainClass>com.yahoo.egads.Egads</mainClass>
			</manifest>
		</archive>
               </configuration>
	          </plugin>


I modified the above code snippet in pom.xml, buld is getting succeeded but the command show the same exception

**Comment by sashaankadibhatla** [comment]
i modified the code in pom.xml , build is succeeded but the command after running shows same exeption

**Comment by jichmi** [comment]
To access this project you can run:

>  'java -Dlog4j.configurationFile=src/test/resources/log4j2.xml -cp target/egads-*-jar-with-dependencies.jar**;target/classes** com.yahoo.egads.Egads src/test/resources/sample_config.ini src/test/resources/sample_input.csv'

but when i type this command other exception occurred：

> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/lo
> g4j/LogManager
>         at com.yahoo.egads.models.tsmm.TimeSeriesAbstractModel.<clinit>(TimeSeri
> esAbstractModel.java:34)
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Unknown Source)
>         at com.yahoo.egads.control.ProcessableObjectFactory.buildTSModel(Process
> ableObjectFactory.java:59)
>         at com.yahoo.egads.control.ProcessableObjectFactory.create(ProcessableOb
> jectFactory.java:26)
>         at com.yahoo.egads.utilities.FileInputProcessor.processInput(FileInputPr
> ocessor.java:30)
>         at com.yahoo.egads.Egads.main(Egads.java:57)
> Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
> 
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown So
> urce)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(U
> nknown Source)
>         at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 7 more

Maybe there are some setting need to be modified
